### ISSUE TITLE
404 Not Found on UI

### ISSUE THREAD

**Issue by embano1** [mreferre/yelb#1]
Hi,

whatever I tried (also with Ingress vs NodePort), hitting the frontend always throws 404 Not Found. May be I´m using the wrong URI? Any trick I´m missing?

![image](https://user-images.githubusercontent.com/15986659/28465163-1a53ae00-6e28-11e7-8161-abe9698a0b68.png)

**Comment by mreferre** [comment]
Thanks Michael for finding this (major!) issue. I think I understand what happened. The environment variable that set the default environment (and nginx file path) was misplaced in the Dockerfile and so the nginx.conf files was misconfigured. I did not catch this in my tests before releasing the code because the browser was caching an older version of the UI that was working. I have [fixed](https://github.com/mreferre/yelb/commit/da9c327113feb63c72596817703560dbee50b8f0) this problem and pushed the new images to the hub. Can you retry to see if it's the same issue?

Thanks!

**Comment by embano1** [comment]
Works like a charm, thx!
![image](https://user-images.githubusercontent.com/15986659/28491069-f39a3a82-6ee9-11e7-8536-77b7869ed7b1.png)
