### ISSUE TITLE
 cnawebapp-minikube-ingress.yaml - Not working

### ISSUE THREAD

**Issue by kevinsteil** [mreferre/yelb#4]
Need to add * after / in ingress config portion of YAML.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: yelb-ui-ingress
   annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / 
spec:
  rules:
    - host: yelb.ing.corp.local
      http:
        paths:
          - path: /*
            backend:
              serviceName: yelb-ui
              servicePort: 80

**Comment by mreferre** [comment]
Hi Kevin. Thanks for opening the issue and sorry for the delay. What problem are you seeing? I haven't tested the minikube yamls in ages but I did put together a quick setup (with this: https://gist.github.com/mreferre/92b2f1ba05c6013a1d3d30de6aaa743f) and using the current yaml it seems to be working just fine (I edited the `/etc/hosts` file manually to make the FQDN point to the VB vm): 

```
ubuntu@ip-172-31-12-124:~/yelb/deployments/platformdeployment/Kubernetes/yaml$ curl yelb.mydomain.com
<!doctype html>
<html>
<head>
    <script src="env.js"></script>
    <meta charset="utf-8">
    <title>Yelb</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico?v=2">
</head>
<body>
<yelb>Loading...</yelb>
<script type="text/javascript" src="inline.bundle.js"></script><script type="text/javascript" src="styles.bundle.js"></script><script type="text/javascript" src="scripts.bundle.js"></script><script type="text/javascript" src="vendor.bundle.js"></script><script type="text/javascript" src="main.bundle.js"></script></body>
</html>
``` 
This is what the ingress looks like:
```
ubuntu@ip-172-31-12-124:~/yelb/deployments/platformdeployment/Kubernetes/yaml$ kubectl get ingress -A 
NAMESPACE   NAME              HOSTS               ADDRESS     PORTS   AGE
default     yelb-ui-ingress   yelb.mydomain.com   10.0.2.15   80      52s
```

I assume the problem you are seeing is due to the annotation you added in your yaml (that I don't have in mine)?

Thanks.
