### ISSUE TITLE
npm dependencies are not getting resolved for dev environment

### ISSUE THREAD

**Issue by munjalt** [mreferre/yelb#42]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/91901360/173397488-d87c3511-6b81-4bcc-86a0-29e43bc83b53.png">

It would be nice if local dev environment can pull docker images that are pre-built or build a local docker container to resolve these dependency issues.

**Comment by mreferre** [comment]
Hi @munjalt. Thanks for your issue. I will admit I have defocused a bit from the [localdevelopment](https://github.com/mreferre/yelb/tree/master/deployments/localdevelopment) deployment option because all the dependencies are very fragile (as you figured). I did have created a [localtest](https://github.com/mreferre/yelb/tree/master/deployments/localtest) deployment options that seems to be similar to what you are describing (which happens to be also similar to a [docker compose deployment](https://github.com/mreferre/yelb/tree/master/deployments/platformdeployment/Docker). 

Is that enough for what you are trying to achieve? I am literally wondering if I should get rid completely of the [localdevelopment](https://github.com/mreferre/yelb/tree/master/deployments/localdevelopment) deployment option to avoid confusion.

**Comment by munjalt** [comment]
@mreferre thanks for the quick response. I did end up using the localtest deployment option. I think that works for folks like me who just want to test out some code and who aren't savvy frontend devs. But someone who wants to play around could get stuck with the dependencies error. That's why I thought I should bring this to your notice. 
But this was really helpful thank you so much!

**Comment by mreferre** [comment]
@munjalt yep I agree with you that the localtest is fine if you want to .. guess what... test it :) but not so much if you want to tweak it. Perhaps I should redo entirely the localdev approach by prescribing to use selected node and ruby images mounting the local folders (instead of demanding that your dev device has the right node and ruby environments installed). This way you could tweak the source code interactively and see what happens (for npm for sure, I don't know if ruby has a fast-reload option though). Thanks! I appreciated you bringing this up (it's something I have been thinking AND THEN PARKING for a long time).
