### ISSUE TITLE
In EC2 platformdeployment is binding redis and PG on 127.0.0.0 after restarting the app server.

### ISSUE THREAD

**Issue by sushreeswetanjali99** [mreferre/yelb#75]
After the sucessful deployment of the CFN the Application work fine as expected. On restart of the app server, we tried to re run the yelb-appserver.sh with the internal IP , but the application throwing error as the app server is looking at 127.0.0.0 for both PG and redis. 

Why is the application not able bind to the right IP after restart

![image](https://user-images.githubusercontent.com/84499149/225956903-21c412c4-1d9e-4896-90b4-f7d519450ccb.png)

**Comment by mreferre** [comment]
Which of the two CFN templates are you using (standalone or distributed)? And what is the command you are launching to restart the app server?

**Comment by sushreeswetanjali99** [comment]
> Which of the two CFN templates are you using (standalone or distributed)? And what is the command you are launching to restart the app server?

I am using distributes cfn templates. 
"ruby yelb-appserver.rb -o 0.0.0.0 &  " this command I have used to restart the server.

**Comment by mreferre** [comment]
You need to export the redis and postgres endpoints before you restart the yelb-appserver. [This](https://github.com/mreferre/yelb/blob/master/deployments/platformdeployment/AWS/EC2/yelb-cloudformation-EC2-distributed-deployment.json#L86-L88) is how the launch of the appserver works in the CFN template. 

You don't need to launch the startup script necessarily because that only tries to set the `SEARCH_DOMAIN` variable (that is used for other type of deployments) BUT you need to set the `YELB_DB_SERVER_ENDPOINT` and `REDIS_SERVER_ENDPOINT` variables.

**Comment by sushreeswetanjali99** [comment]
I have run the two export commands from the command line,

export REDIS_SERVER_ENDPOINT=ip-172-x-x-x.ec2.internal
export YELB_DB_SERVER_ENDPOINT=ip-172-x-x-x.ec2.internal

and then executed the ruby script

ruby yelb-appserver.rb -o 0.0.0.0 &

But the app server still tries to connect to the Redis cache over 127.0.0.1:6379. It specifically fails for the api/getstats, api/pageviews, api/getvotes, etc. 

Is there any specific configuration file to be updated? And, also where is the ruby log file located on the linux system?

Thanks in advance!

**Comment by mreferre** [comment]
Ouch. My bad. The CFN template does NOT call the `setup.sh` script in the `yelb-appserver` folder. It calls another script (`yelb-appserver.sh`) in the [Linux deployment folder](https://github.com/mreferre/yelb/blob/master/deployments/platformdeployment/Linux/yelb-appserver.sh). This script actually setup the app server on Linux. 

You do NOT need to re-run the entire script because the code is already installed but you are probably only missing the setting of the `RACK_ENV` variable that is set to `custom` in that script ([here](https://github.com/mreferre/yelb/blob/master/deployments/platformdeployment/Linux/yelb-appserver.sh#L9)). 

This tells ruby to start the code and look for the variables you are exporting ([here](https://github.com/mreferre/yelb/blob/master/yelb-appserver/yelb-appserver.rb#L57-L65)). Long story short, if you run these commands it should work: 

```
export REDIS_SERVER_ENDPOINT=ip-172-x-x-x.ec2.internal
export YELB_DB_SERVER_ENDPOINT=ip-172-x-x-x.ec2.internal
export RACK_ENV="custom"
ruby /yelb-setup/yelb/yelb-appserver/yelb-appserver.rb -o 0.0.0.0 &
```

Can you try?

**Comment by mreferre** [comment]
Excellent. Thanks for your patience!
