### ISSUE TITLE
Possible to deploy using service connect on ecs?

### ISSUE THREAD

**Issue by aleyrizvi** [mreferre/yelb#86]
Hello,
I was wondering if possible to deploy using service connect and not using awsvpc network?

**Comment by mreferre** [comment]
It is. I have tested it (via a manual console configuration - I have not updated the IaC assets in this repo). Service Connect would allow to get rid of [this](https://github.com/mreferre/yelb/blob/master/yelb-appserver/startup.sh#L3-L7) hack. 

There is a caveat though. Startup order is important because of the way Service Connect registers services. You need to start the backend first, than the appserver and finally the ui. If you start them in the wrong order (e.g. ui first, appserver next) the ui won't know how to resolve the appserver. Other than this it works great (based on my tests)

**Comment by aleyrizvi** [comment]
Thank you @mreferre 

Another finding : You cannot use network mode : default. 
Even if the default mode is bridge on linux, you have to explicitly specify it to be bridge or awsvpc. 

It wasted my 2 days struggling with my task definitions. :)
